# Generated by Django 3.1.7 on 2021-02-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(choices=[('Bubble', 'Bubble'), ('Insertion', 'Insertion'), ('Merge', 'Merge'), ('Quick_sort', 'Quick sort')], max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
